"""Publish promoted baseline guidance into agent-specific generated files."""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass
from pathlib import Path

from .baseline_promote import PROMOTION_BEGIN, PROMOTION_END, parse_promoted_blocks
from .baseline_settings import load_baseline_settings
from .baseline_types import BaselineSettings
from .config import ArchiveConfig

GLOBAL_SOURCES = (
    "engineering-guardrails.md",
    "regression-frameworks.md",
    "repo-workflows.md",
    "prompt-patterns.md",
)

AGENT_TARGETS = {
    "codex": ("agents/codex/AGENTS.generated.md", "Codex", "AGENTS.md"),
    "claude": ("agents/claude/CLAUDE.generated.md", "Claude", "CLAUDE.md"),
    "vscode": ("agents/vscode/copilot-instructions.generated.md", "VS Code", "copilot instructions"),
}


@dataclass(frozen=True)
class PromotedRule:
    rule_id: str
    title: str
    body: str
    source_file: str


def strip_promotion_markers(block: str) -> str:
    begin_prefix = PROMOTION_BEGIN.split("{", 1)[0]
    end_prefix = PROMOTION_END.split("{", 1)[0]
    lines = []
    for line in block.splitlines():
        stripped = line.strip()
        if stripped.startswith(begin_prefix) or stripped.startswith(end_prefix):
            continue
        lines.append(line)
    return "\n".join(lines).strip()


def extract_rule_title(block: str, rule_id: str) -> str:
    for line in strip_promotion_markers(block).splitlines():
        if line.startswith("## "):
            return line[3:].strip()
    return rule_id


def collect_promoted_rules(settings: BaselineSettings) -> list[PromotedRule]:
    rules: list[PromotedRule] = []
    global_dir = settings.root / "global"
    for filename in GLOBAL_SOURCES:
        path = global_dir / filename
        if not path.exists():
            continue
        blocks = parse_promoted_blocks(path.read_text(encoding="utf-8"))
        for rule_id, block in sorted(blocks.items()):
            rules.append(
                PromotedRule(
                    rule_id=rule_id,
                    title=extract_rule_title(block, rule_id),
                    body=strip_promotion_markers(block),
                    source_file=f"baseline/global/{filename}",
                )
            )
    return rules


def render_rule_section(rule: PromotedRule) -> str:
    text_lines = []
    for line in rule.body.splitlines():
        if line.startswith("## "):
            continue
        text_lines.append(line)
    text = "\n".join(text_lines).strip()
    return (
        f"### {rule.title}\n\n"
        f"**Source:** `{rule.source_file}` · **ID:** `{rule.rule_id}`\n\n"
        f"{text}\n"
    )


def render_agent_document(
    agent_key: str,
    rules: list[PromotedRule],
    generated_at: str,
) -> str:
    rel_path, agent_name, hand_written_target = AGENT_TARGETS[agent_key]
    lines = [
        f"# Generated {agent_name} Engineering Baseline",
        "",
        f"> Auto-generated by `baseline publish` on {generated_at}.",
        f"> Review promoted rules in `baseline/global/` before mirroring into `{hand_written_target}`.",
        "",
        "<!-- baseline:generated:begin -->",
        "",
        "## Promoted Guardrails",
        "",
    ]
    if not rules:
        lines.append("_No promoted guardrails found. Run `baseline promote` first._")
    else:
        for rule in rules:
            lines.append(render_rule_section(rule))
            lines.append("")
    if agent_key == "codex":
        lines.extend(
            [
                "## Usage",
                "",
                "Mirror the sections above into project `AGENTS.md` once trusted, or include this",
                "generated file via a short pointer section with clear begin/end markers.",
                "",
            ]
        )
    elif agent_key == "claude":
        lines.extend(
            [
                "## Usage",
                "",
                "Mirror the sections above into project `CLAUDE.md` once trusted. Keep generated",
                "content separate from hand-written conventions until calibration proves useful.",
                "",
            ]
        )
    else:
        lines.extend(
            [
                "## Usage",
                "",
                "Use as VS Code copilot instructions once the publisher is trusted on this machine.",
                "",
            ]
        )
    lines.append("<!-- baseline:generated:end -->")
    return "\n".join(lines).rstrip() + "\n"


def publish_agent_files(
    settings: BaselineSettings,
    agents: tuple[str, ...] | None = None,
    generated_at: str | None = None,
) -> dict[Path, str]:
    selected = agents or tuple(AGENT_TARGETS)
    unknown = [agent for agent in selected if agent not in AGENT_TARGETS]
    if unknown:
        raise SystemExit(f"Unknown agent targets: {', '.join(unknown)}")
    rules = collect_promoted_rules(settings)
    timestamp = generated_at or dt.date.today().isoformat()
    outputs: dict[Path, str] = {}
    for agent_key in selected:
        rel_path, _, _ = AGENT_TARGETS[agent_key]
        path = settings.root / rel_path
        outputs[path] = render_agent_document(agent_key, rules, timestamp)
    return outputs


def baseline_publish(
    config: ArchiveConfig,
    dry_run: bool = False,
    agents: tuple[str, ...] | None = None,
) -> int:
    settings = load_baseline_settings(config)
    outputs = publish_agent_files(settings, agents=agents)
    if not outputs:
        print("No agent targets configured.")
        return 0
    for path, content in outputs.items():
        if dry_run:
            print(f"Would write {path}")
            print(content)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"Wrote {path}")
    return 0