"""Markdown rendering for candidate reports and calibration summaries."""

from __future__ import annotations

import datetime as dt
from collections import Counter
from pathlib import Path
from typing import Any

from .baseline_types import BaselineSettings, Prediction, TextSignal, parse_verdict


def render_candidate_report(
    settings: BaselineSettings,
    index_records: list[dict[str, Any]],
    source_counts: Counter[str],
    kind_counts: Counter[str],
    project_hits: Counter[str],
    text_signals: dict[str, list[TextSignal]],
    predictions: list[Prediction],
    max_sessions: int,
    feedback_path: Path | None,
) -> str:
    scanned_count = len(index_records) if max_sessions == 0 else min(max_sessions, len(index_records))
    lines = [
        f"# Baseline Candidate Extraction ({dt.date.today().isoformat()})",
        "",
        "Status: proposed",
        "Generated by: `python .\\tools\\agent_archive.py baseline suggest`",
        "",
        "## Summary",
        "",
        f"- Indexed sessions: `{len(index_records)}`",
        f"- Markdown sessions scanned for text signals: `{scanned_count}`",
        f"- Canonical agents represented: `{len(source_counts)}`",
        f"- Feedback file: `{feedback_path or 'none'}`",
        "",
        "## Agent Mix",
        "",
    ]
    for source, count in source_counts.most_common():
        lines.append(f"- `{source}`: {count}")
    lines.extend(["", "## Source Detail (per-machine)", ""])
    # Build per-source breakdown from index records to show how canonical
    # agents break down across machines.
    source_raw: Counter[str] = Counter()
    for record in index_records:
        source_raw[str(record.get("source", ""))] += 1
    for source, count in source_raw.most_common():
        lines.append(f"- `{source}`: {count}")
    lines.extend(["", "## Pilot Project Signals", ""])
    if project_hits:
        for slug, count in project_hits.most_common():
            lines.append(f"- `{slug}`: {count}")
    else:
        lines.append("- No configured pilot project names were detected in the archive index yet.")
    lines.extend(["", "## Text Signal Counts", ""])
    for group, signals in text_signals.items():
        lines.append(f"- `{group}`: {sum(signal.count for signal in signals)} hits across {len(signals)} scanned sessions")
    lines.extend(["", "## Predictions And Candidate Rules", ""])
    for prediction in predictions:
        lines.extend(render_prediction(prediction))
    lines.extend(
        [
            "",
            "## Calibration Loop",
            "",
            "Copy `baseline/calibration/feedback.example.toml` to `baseline/calibration/feedback.toml`, then mark each",
            "prediction as `accept`, `edit`, or `reject`. Rerun this command with `--feedback` to let the next report",
            "show where the system was right, wrong, or too vague.",
            "",
            "The first version only adjusts confidence and status. Later versions should compare prediction history",
            "against accepted feedback and make the next proposal sharper.",
        ]
    )
    return "\n".join(lines) + "\n"


def render_prediction(prediction: Prediction) -> list[str]:
    lines = [
        f"### {prediction.title}",
        "",
        f"Prediction id: `{prediction.id}`",
        f"Status: {prediction.status}",
        f"Scope: {prediction.scope}",
        f"Risk: {prediction.risk}",
        f"Category: {prediction.category}",
        f"Confidence: {prediction.confidence:.2f}",
        f"Feedback: {prediction.feedback}",
        "",
        "Evidence:",
    ]
    for item in prediction.evidence:
        lines.append(f"- {item}")
    lines.extend(
        [
            "",
            "Suggested baseline text:",
            prediction.text,
            "",
            "Promotion:",
            "- [ ] Accept",
            "- [ ] Edit and accept",
            "- [ ] Reject",
            "- [ ] Project-specific only",
            "",
        ]
    )
    return lines


def render_calibration_summary(
    prediction_data: dict[str, Any],
    feedback_map: dict[str, dict[str, str]],
    feedback_path: Path,
    prediction_path: Path,
) -> str:
    predictions = prediction_data.get("predictions", [])
    accepted: list[str] = []
    edited: list[str] = []
    rejected: list[str] = []
    missing: list[str] = []
    for prediction in predictions:
        prediction_id = prediction.get("id", "")
        feedback = feedback_map.get(prediction_id)
        if not feedback:
            missing.append(prediction_id)
            continue
        verdict = parse_verdict(feedback)
        if verdict == "accept":
            accepted.append(prediction_id)
        elif verdict == "edit":
            edited.append(prediction_id)
        elif verdict == "reject":
            rejected.append(prediction_id)
    lines = [
        f"# Calibration Summary ({dt.date.today().isoformat()})",
        "",
        f"- Prediction run: `{prediction_data.get('run_id', prediction_path.stem)}`",
        f"- Prediction sidecar: `{prediction_path}`",
        f"- Feedback file: `{feedback_path}`",
        f"- Predictions reviewed: `{len(predictions)}`",
        f"- Accepted: `{len(accepted)}`",
        f"- Edited: `{len(edited)}`",
        f"- Rejected: `{len(rejected)}`",
        f"- Awaiting feedback: `{len(missing)}`",
        "",
        "## Accepted",
        "",
        *render_id_list(accepted),
        "",
        "## Edit Requested",
        "",
        *render_id_list(edited),
        "",
        "## Rejected",
        "",
        *render_id_list(rejected),
        "",
        "## Awaiting Feedback",
        "",
        *render_id_list(missing),
        "",
        "## Next Correction",
        "",
        "Use accepted predictions as stronger priors, rewrite edited predictions before promotion, and suppress",
        "or reframe rejected predictions in the next candidate report.",
    ]
    return "\n".join(lines) + "\n"


def render_id_list(values: list[str]) -> list[str]:
    if not values:
        return ["- None"]
    return [f"- `{value}`" for value in values]
